name: sqlite_fs
description: pkg:file file system backed by pkg:sqlite3
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  file: ^7.0.1
  sqlite3: ^2.7.5
  path: ^1.9.1
  collection: ^1.19.1

dev_dependencies:
  flutter_lints: ^5.0.0
  file_testing: ^3.0.2
  test: ^1.25.15
